package moe.rainbowyang.util

const val API_KEY = "api_key"
const val SYMBOL = "symbol"
const val SIZE = "size"
const val SINCE = "since"
const val TYPE = "type"
const val SIGN = "sign"
const val PRICE = "price"
const val AMOUNT = "amount"

const val BUY="buy"
const val SELL="sell"

const val BTC = "btc"
const val USDT = "usdt"
const val OKB = "okb"
const val XRP = "xrp"

const val ONE_MIN = "1min"
const val THREE_MIN = "3min"
const val FIVE_MIN = "5min"
const val FIFTEEN_MIN = "15min"
const val THIRTY_MIN = "30min"
const val ONE_HOUR = "1hour"
const val TWO_HOUR = "2hour"
const val FOUR_HOUR = "4hour"
const val SIX_HOUR = "6hour"
const val TWELVE_HOUR = "12hour"
const val ONE_DAY = "1day"
const val ONE_WEEK = "1week"
